# netlify.toml

[build]
command = "npm run build" # Replace this with your build command if different
publish = "build" # The folder to publish after build (typically "build" for React)

[[redirects]]
force = true
from = "http://*"
status = 301
to = "https://:splat"
